import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Web3 from "web3";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getLibrary = (provider: any) => {
  if (!provider) {
    console.error("Provider is not available");
    return null;
  }
  console.log(provider, 'provider');
  return new Web3(provider);
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      {/* <Web3ReactProvider getLibrary={getLibrary}> */}

      <body className={inter.className}>{children}</body>
      {/* </Web3ReactProvider> */}
    </html>
  );
}
